connection.string: "Data Source=localhost;Initial Catalog=DemoCDC;Persist Security Info=True;User ID=sa;Password=CDCpassw0rd!;"
throttle.ms: 5000
tables:
  - name: Employee
    schema: dbo
    columns:
    - name: ID
      value: "{{randomizer.number(1,1000)}}"
    - name: Name
      value: "{{name.firstname(Male)}}"
    - name: Salary
      value: "{{randomizer.number(1,1000)}}"
    - name: expedicion
      format: array
      items:
       - "887888"
       - "788778"
    - name: payload
      format: json
      object:
        id: "{{randomizer.number(1000, 9999)}}"
        ancho: "{{randomizer.number(10, 100)}}"
        alto: "{{randomizer.number(10, 500)}}"
        largo: "{{randomizer.number(10, 1000)}}"
        peso: "{{randomizer.number(100, 9999)}}"

#  - name: tbEventos
#    schema: dbo
#    columns:
#    - name: dtEvento
#      value: "{{date.Future}}"
#    - name: tpEvento
#      value: Bulto
#    - name: Origem
#      value: Sorter
#    - name: Dados
#      format: json
#      object:
#        id: "{{name.firstname(Female)}}"
#        rampa: "{{name.firstname(Female)}}"
#        fecha: "{{name.firstname(Female)}}"
#        modo: 1
