connection.string: "Data Source=localhost;Initial Catalog=DemoCDC;Persist Security Info=True;User ID=sa;Password=CDCpassw0rd!;"
database.provider: sqlserver
#connection.string: "User ID=USER;Password=passw0rd;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=DB)));Persist Security Info=False"
#database.provider: oracle
throttle.ms: 5000
tables:
  - name: Employee
    schema: dbo
    columns:
    - name: ID
      value: "{{randomizer.number(1,1000)}}"
    - name: Name
      value: "{{name.firstname(Male)}}"
    - name: Salary
      value: "{{randomizer.number(1,1000)}}"
    - name: office
      format: array
      items:
       - "ONE"
       - "TWO"
       - "ALL"
    - name: payload
      format: json
      object:
        id: "{{randomizer.number(1000, 9999)}}"
        ancho: "{{randomizer.number(10, 100)}}"
        alto: "{{randomizer.number(10, 500)}}"
        largo: "{{randomizer.number(10, 1000)}}"
        peso: "{{randomizer.number(100, 9999)}}"
